---
#ansible -m debug -a "var=hostvars" localhost
  
- debug: msg={{ hostvars[inventory_hostname].rack_name }}

- name: create rack buckets
  command: ceph osd crush add-bucket "{{ hostvars[inventory_hostname].rack_name }}" rack
  with_items: "{{ hostvars }}"
  
- name: move osd server to rack bucket
  command: ceph osd crush move "{{ ansible_hostname }} rack={{ hostvars[inventory_hostname].rack_name }}"
  with_items: "{{ hostvars }}"
  
- name: move rack bucket to crush root
  command: ceph osd crush move "{{ hostvars[inventory_hostname].rack_name }} root={{ hostvars[inventory_hostname].disk_type }}"
  with_items: "{{ hostvars }}"
  
- name: prepare rack rules
  command: echo "{{ hostvars[inventory_hostname].rack_name }}-rule {{ hostvars[inventory_hostname].disk_type }}"
  with_items: "{{ hostvars }}"
  register: racks_and_disk_types
  
- name: create crush rules
  command: ceph osd crush rule create-simple "{{ item }}" rack
  with_items: "{{ racks_and_disk_types | unique }}"
